name:                fpainter
version:             0.1.0.0

dependencies:
- base >=4.7 && < 5
- codeworld-api
- text
- containers
- array

library:
  source-dirs: src

executables:
  code-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - fpainter

tests:
  code-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpainter
